public/js/p3/store/HeatmapDataTypes.js, public/js/p3/store/TranscriptomicsGeneMemoryStore.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/ProteinFamiliesFilterGrid.js, public/js/p3/widget/TranscriptomicsGeneContainer.js, public/js/p3/widget/TranscriptomicsGeneFilterGrid.js, public/js/p3/widget/TranscriptomicsGeneHeatmapContainer.js
- bug fix on GridContainer
- TranscriptomicsGene page (experiment page)
=> working commit

.gitmodules, app.js, views/javascript.ejs
To use the blessedly coffee free MSA.
=> MSA update

.gitmodules, public/js/p3/store/PathwayMapMemoryStore.js, public/js/p3/store/PathwayMemoryStore.js, public/js/p3/widget/ActionBar.js, public/js/p3/widget/FilterContainerActionBar.js, public/js/p3/widget/PathwayMapContainer.js, public/js/p3/widget/PathwayMapKegg.js, public/js/p3/widget/PathwayMapKeggContainer.js, public/js/p3/widget/PathwaysContainer.js, public/js/p3/widget/PathwaysMemoryGrid.js, public/js/p3/widget/PathwaysMemoryGridContainer.js, public/js/p3/widget/viewer/PathwayMap.js, views/header.ejs
- update font-awesome version
- hide logs
- pathway map
- correct .gitmodule protocol
=> patway map & etc

public/js/p3/resources/p3.css, public/js/p3/store/IdMappingMemoryStore.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/IDMappingGrid.js, public/js/p3/widget/IDMappingGridContainer.js, public/js/p3/widget/PathwayMapKegg.js, public/js/p3/widget/ProteinFamiliesHeatmapContainer.js, public/js/p3/widget/templates/IDMapping.html, public/js/p3/widget/viewer/IDMapping.js
ID mapping button in selection Action sends a request to /viewer/IDMapping/ page
=> implemented IDMapping

public/js/p3/store/GeneExpressionChartMemoryStore.js, public/js/p3/store/GeneExpressionMetadataChartMemoryStore.js, public/js/p3/widget/GeneExpressionChartContainer.js, public/js/p3/widget/GeneExpressionContainer.js, public/js/p3/widget/GeneExpressionMetadataChartContainer.js
Still need to work on the following 
1) The labels on the bar chart (count number) need to display as integers 
2) show "All" or "Top 5" options.
=> Implemented feature Transcriptomics tab bar charts and pie charts.

public/js/p3/widget/PathwayMapHeatmapContainer.js, public/js/p3/widget/ProteinFamiliesHeatmapContainer.js
- heatmap actions: disable buttons when on feature was selected
- deduplicate featues
=> small bug fixes

public/js/p3/resources/WorkspaceManager.css, public/js/p3/store/GeneExpressionMemoryStore.js, public/js/p3/widget/DownloadTooltipDialog.js, public/js/p3/widget/GeneExpressionContainer.js, public/js/p3/widget/GeneExpressionGrid.js, public/js/p3/widget/GeneExpressionGridContainer.js
There could be a bug at data api or some other place that causes an empty file returned. Dustin will take look at this bug.
=> Feature Transcriptomics Tab: Implemented top level download button and table grid side download button.

public/js/p3/widget/GenomeBrowser.js, public/js/p3/widget/Phylogeny.js, public/js/release/build-report.txt, public/js/release/p3/widget/GenomeBrowser.js, public/js/release/p3/widget/Phylogeny.js
-default zoom and location
-remove non-functional buttons
=> phylogeny viewer and genome browser updates

public/js/p3/resources/SummaryWidget.css, public/js/p3/widget/AMRPanelMetaSummary.js, public/js/p3/widget/D3HorizontalBarChart.js, public/js/p3/widget/FeatureListOverview.js, public/js/p3/widget/FeatureOverview.js, public/js/p3/widget/FunctionalProfile.js, public/js/p3/widget/TaxonomyProfile.js, public/js/p3/widget/templates/FeatureListOverview.html, public/js/p3/widget/templates/FeatureOverview.html
- first version
- will implement more detail soon
=> Function profile and Taxonomy profile in feature list overview

public/js/p3/widget/viewer/MSA.js
Requires submodule update of phyloview
=> MSA selection update

public/js/p3/widget/TaxonNameSelector.js, public/js/p3/widget/app/Annotation.js
=> Ranking of taxonNameSelector and special character safety

public/js/p3/widget/app/Assembly.js, public/js/p3/widget/app/templates/Assembly.html
platform selection for single and paired end reads. some other parameters. fix/enhance mouse over on library list.
=> Assembly platform and backend enhancements

public/js/p3/widget/app/help/GenomeAssemblyHelp.html, public/js/p3/widget/app/templates/Assembly.html
Small updates for assembly help. Still need to fix general tool help header formatting.
=> contraints and help text for platform coverage update assembly

public/js/p3/resources/SummaryWidget.css, public/js/p3/widget/D3SingleGeneViewer.js, public/js/p3/widget/FeatureOverview.js
- features clickable
- remove feature_type source
=> single gene viewer

public/js/p3/widget/app/help/RNASeqHelp.html
=> RNASeq help fix

public/js/p3/store/GeneExpressionChartMemoryStore.js, public/js/p3/widget/GeneExpressionChartContainer.js
In the transcriptomics bar chart, added <-2.0 and >=2.0 columns when there is data
=> Bug fix for #424

public/help/GenomeAnnotationHelp, public/help/GenomeAssemblyHelp, public/help/GenomeComparisonHelp
=> Augmented help files

public/js/p3/store/IDMappingMemoryStore.js, public/js/p3/widget/IDMappingGrid.js
=> ID mapping result

public/js/p3/widget/JobManager.js, public/js/p3/widget/Uploader.js, public/js/p3/widget/WorkspaceBrowser.js
Can now overwrite files:
Could be improved later with "apply to all" option.
=> overwriting files and addressing some issues

public/js/p3/resources/p3.css, public/js/p3/widget/AntibioticOverview.js, public/js/p3/widget/DataItemFormatter.js, public/js/p3/widget/ExternalItemFormatter.js, public/js/p3/widget/templates/AntibioticOverview.html, public/js/p3/widget/viewer/Feature.js
- add publications panel
- add synonyms panel with keyword style class
- minor fixes/changes
=> antibiotic overview page

public/js/p3/util/QueryToEnglish.js, public/js/p3/widget/viewer/SpecialtyGeneList.js, public/js/p3/widget/viewer/TaxonList.js, public/js/p3/widget/viewer/TranscriptomicsExperimentList.js
Global Search result: the large number of feature id search made the Feature Table on Feature List page not viewable #1461
Genome List View: the genome ids are not showing up at the perspective panel #1460.
=> Fixed bugs: #1461 and #1460 

public/js/p3/app/p3app.js
This is a sort of prereq for the sharing functionality since we only want the "home" workspace showing up in the workspace drown.
=> only display home and special folders in workspace dropdown

public/js/p3/store/TranscriptomicsGeneMemoryStore.js
This is needed for PATRIC april release
=> Fix for #1494 Transcripomics heatmap doesn't work for host data

public/js/p3/widget/app/Expression.js, public/js/p3/widget/app/templates/Expression.html
Get source_id_type from submission form. Again.
=> Differential expression app spec id source type and get pmid

public/js/p3/widget/DownloadTooltipDialog.js
added fasta options in speciality genes download.
=> fixed issue #1452 and #1496

public/js/p3/widget/GenomeNameSelector.js
=> fix for reference and representative filter

public/js/p3/widget/PathwaySummaryGridContainer.js, public/js/p3/widget/WorkspaceBrowser.js
For issue #1447, "Features" and "Group" icons were added to the action bar. While doing the testing, a small problem was found (#1515) and it was fixed as well.
=> Fixed issue #1447 and #1515

public/js/p3/widget/DataItemFormatter.js, public/js/p3/widget/SpecialtyGeneGrid.js, public/js/p3/widget/SpecialtyGeneGridContainer.js, public/js/p3/widget/viewer/Antibiotic.js
=> add antibiotics class and antibiotics in facet, grid, and detail panel

public/js/p3/widget/Confirmation.js, public/js/p3/widget/DataItemFormatter.js, public/js/p3/widget/GenomeOverview.js, public/js/p3/widget/InputList.js, public/js/p3/widget/MetaEditor.js
=> checkpoint for meta editing

public/js/p3/WorkspaceManager.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/WorkspaceObjectSelector.js
...and improve icons in obj selector.  
I'm just making this PR in the event alpha is updated.  It's not critical and more changes will be coming.
=> make the default path for object selector the user's list of workspaces

public/js/p3/widget/AdvancedSearch.js, public/js/p3/widget/GlobalSearch.js, public/js/p3/widget/templates/GlobalSearch.html, public/js/p3/widget/viewer/MSA.js
Added Feature, FeatureList, Genome, GenomeList action items.
=> Implemented an enhanced feature for MSA: Launch feature OR genome view from MSA #1293

public/js/p3/widget/app/PhylogeneticTree.js, public/js/p3/widget/app/help/PhylogeneticTreeHelp.html, public/js/p3/widget/app/templates/PhylogeneticTree.html
UI is working up to generating JSON parameters.
Need to test with back-end service when it is available.
Need edit on the help text.
=> Phylogenetic Tree Building Service UI.

public/js/p3/widget/DataItemFormatter.js
sequence tab: link genome id to genome overview page.
=> fixed issue #1586

public/js/p3/widget/viewer/JobResult.js
Fix for:
https://github.com/PATRIC3/patric3_website/issues/1597
=> modified JRV to pull result objects from the hidden folder vs the autoMetadata

public/js/p3/widget/WorkspaceBrowser.js
accidentally commented out line
=> fix row highlighting on folder change

public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/viewer/JobResult.js, public/js/p3/widget/viewer/Seq.js
It looks like some changes didn't survive the merges, so adding them back in very specifically.
=> added in job result viewer and track streaming changes missed by merge

public/js/p3/widget/app/PhylogeneticTree.js, public/js/p3/widget/app/templates/PhylogeneticTree.html
fix message and code formatting
=> phylogenetic tree

public/js/p3/WorkspaceManager.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/viewer/File.js, public/js/p3/widget/viewer/Seq.js
One more fix for an issue Bob brought up with the track streaming where they are not set to compact mode by default.
=> set the JBrowse tracks to compact mode + bug fixes

public/js/p3/widget/app/templates/PhylogeneticTree.html
changed default for tree to FastTree with no refinement
=> address issue 1634

public/js/p3/widget/DataItemFormatter.js
Prevent breaking down to each letter
=> handle when list field has a string value

public/js/p3/widget/viewer/GenomeGroup.js, public/js/p3/widget/viewer/Taxonomy.js, public/js/p3/widget/viewer/_GenomeList.js
- use POST method for this query. add limit() to read all related
=> improvement

public/js/p3/widget/WorkspaceBrowser.js
Turn on BAM streaming for variation
=> Turn on BAM streaming for Variation. Still need to look at VCF.

public/js/p3/widget/GroupExplore.js
Highlight and update proper messages.
=> Bug fix: Venn Diagram-creating group from selected region does not give any indication that it is working #1698

public/js/p3/widget/AMRPanelGridContainer.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/IDMappingAppResultGridContainer.js, public/js/p3/widget/InteractionGraphContainer.js, public/js/p3/widget/InteractionGridContainer.js, public/js/p3/widget/PathwaySummaryGridContainer.js, public/js/p3/widget/Phylogeny.js, public/js/p3/widget/ProteinFamiliesGridContainer.js, public/js/p3/widget/SpecialtyGeneGrid.js, public/js/p3/widget/TranscriptomicsGeneHeatmapContainer.js, public/js/p3/widget/WorkspaceBrowser.js
=> fixed issue #1024 & #1717

public/js/p3/widget/GridContainer.js, public/js/p3/widget/PageGrid.js, public/js/p3/widget/viewer/FASTA.js
there was a bug in FASTA viewer download button.
=> addressed issue #1717 and multiple pages selection

public/js/p3/widget/GridContainer.js
de-selection after select all or multiple pages selection
=> addressed issue #1731

public/js/p3/widget/Phylogeny.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/viewer/PhylogeneticTree.js
View tree jobs in the tree viewer.
=> phylogenetic tree viewer for phylogenetic tree jobs

public/js/p3/widget/CopyTooltipDialog.js
=> Added column blacklist for copy to clipboard feature

public/js/p3/widget/viewer/JobResult.js
Let's the user resize the split as they like.
=> Add splitter to Job Results page between header and file browser 

public/js/p3/widget/WorkspaceBrowser.js
@hyoo this is the fix for production (for the workshop).
=> patch for modelseed linkage

public/js/p3/widget/FeatureGridContainer.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/SpecialtyGeneGridContainer.js, public/js/p3/widget/viewer/_FeatureList.js
=> fix a few issues

public/js/p3/widget/ItemDetailPanel.js, public/js/p3/widget/Uploader.js
For rebecca's requested rerooted trees and bob's requested ability to upload newick and view.
=> ability to change newick file types

public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/viewer/GenomeAnnotation.js
Adds the blue nav buttons and the additional labels in the result page
=> added GenomeAnnotationGenbank as a Genome Annotation job 

public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/viewer/GenomeAnnotation.js
=> Revert "added GenomeAnnotationGenbank as a Genome Annotation job "

public/js/p3/resources/dlp.css
This is the final 404/deadlink found on PATRIC.
=> Removed reference to 404 asset

public/js/p3/widget/viewer/MSA.js
Fixes critical bug https://github.com/PATRIC3/patric3_website/issues/1804
=> bug fix ordering MSA

public/js/p3/widget/app/AppBase.js
=> fixed a typo

public/js/p3/store/IDMappingAppMemoryStore.js
=> resolves issue #1818

public/js/p3/widget/app/Assembly.js, public/js/p3/widget/app/Rnaseq.js, public/js/p3/widget/app/Tnseq.js, public/js/p3/widget/app/Variation.js
Fixed this for assembly, variation, rna-seq, tn-seq services. Partially address PATRIC3/patric3_webiste#1855
=> Do not allow same file in paired end reads

public/js/p3/resources/WorkspaceManager.css, public/js/p3/widget/WorkspaceGrid.js, public/js/p3/widget/WorkspaceObjectSelector.js
Would be good to get this to production for anybody who is used to clicking workspace icons.
=> rename class and fixing workspace object icon link

public/js/p3/widget/app/MetagenomeBinning.js, public/js/p3/widget/app/templates/MetagenomeBinning.html
address issues PATRIC3/patric3_webiste#1831 and PATRIC3/patric3_webiste#1783, also enforce OR logic on the UI.
=> bug fix and enhancement on metagenome binning service UI

public/js/p3/widget/SelectionToGroup.js
This features is already on prod, but I apparently forgot one line.
=> fix bug in PATRIC3/patric3_website#1813

public/js/p3/widget/CircularViewerContainer.js
Please also include the updated the circulus submodule for new builds
=>  Enhancements for circular genome viewer

public/js/p3/widget/LoginForm.js, public/js/p3/widget/Uploader.js, public/js/p3/widget/templates/LoginForm.html, public/js/p3/widget/templates/Uploader.html
https://github.com/PATRIC3/patric3_website/issues/1630
=> User svc: allows reset password with email or username

public/js/p3/widget/Uploader.js, public/js/p3/widget/app/Annotation.js, public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/Assembly.js, public/js/p3/widget/app/ComprehensiveGenomeAnalysis.js, public/js/p3/widget/app/MetagenomeBinning.js, public/js/p3/widget/app/templates/Annotation.html, public/js/p3/widget/app/templates/Assembly.html, public/js/p3/widget/app/templates/ComprehensiveGenomeAnalysis.html, public/js/p3/widget/app/templates/MetagenomeBinning.html, public/js/p3/widget/templates/Uploader.html
https://github.com/PATRIC3/patric3_website/issues/1948
=> prevent slashes in output names for Annotation, Assembly, Comprehensive Genome Analysis, MetagenomeBinning

public/js/p3/widget/Uploader.js, public/js/p3/widget/app/templates/PhylogeneticTree.html, public/js/p3/widget/app/templates/Reconstruct.html, public/js/p3/widget/app/templates/Rnaseq.html, public/js/p3/widget/app/templates/SeqComparison.html, public/js/p3/widget/app/templates/SimpleAnnotation.html, public/js/p3/widget/app/templates/Tnseq.html, public/js/p3/widget/app/templates/Variation.html, public/js/p3/widget/templates/Uploader.html
https://github.com/PATRIC3/patric3_website/issues/1948
=> More output names - preventing slashes, phylog..., reconstruct, rnaseq, seqComp, simple annotation, tnseq, and variation

public/js/p3/widget/Uploader.js, public/js/p3/widget/WorkspaceObjectSelector.js, public/js/p3/widget/templates/Uploader.html, public/js/p3/widget/templates/WorkspaceObjectSelector.html
https://github.com/PATRIC3/patric3_website/issues/1878
https://github.com/PATRIC3/patric3_website/issues/1175
=> file uploader prevents slashes on filenames, also select boxes have a sort button to sort alphabetically

public/js/p3/widget/Uploader.js, public/js/p3/widget/WorkspaceObjectSelector.js, public/js/p3/widget/templates/Uploader.html, public/js/p3/widget/templates/WorkspaceObjectSelector.html
https://github.com/PATRIC3/patric3_website/issues/1947
=> Upload png fixed

public/js/p3/widget/DownloadTooltipDialog.js, public/js/p3/widget/Uploader.js, public/js/p3/widget/WorkspaceObjectSelector.js, public/js/p3/widget/templates/Uploader.html, public/js/p3/widget/templates/WorkspaceObjectSelector.html
https://github.com/PATRIC3/patric3_website/issues/1939
=> Fix download from action bar

public/js/p3/widget/viewer/File.js
This is a more industrial strength html view w/ @dmachi
=> html viewer adjustment overruns

public/js/p3/widget/AdvancedDownload.js
make sure at least one file type is selected
=> fixed issue: PATRIC3/patric3_webiste#1894

public/js/p3/resources/home-new.css, views/home-new.ejs, views/index-new.ejs
Style updates based on another mockup. Looking for reviews during workshop.
- Announcements Dot Navigation and .json incoming.
=> Style Updates

public/js/p3/resources/home-new.css
**Headings** - Roboto 700
**Paragraph** - Didact Gothic 400
**Links & Buttons** - Default Arial
=> Typography Update

public/js/p3/resources/home-new.css, views/home-new.ejs, views/home.ejs
=> Homepage Updates - 5/24/18

public/js/p3/widget/GridContainer.js
=> removing genome sharing limit

public/js/p3/widget/app/GenomeDistance.js, public/js/p3/widget/app/templates/GenomeDistance.html
Enable fastq files in the genome distance app.
=> genome distance enable read files

public/js/p3/widget/AMRPanelGridContainer.js, public/js/p3/widget/CorrelatedGenesGridContainer.js, public/js/p3/widget/FeatureGridContainer.js, public/js/p3/widget/GenomeGridContainer.js, public/js/p3/widget/GridContainer.js, public/js/p3/widget/InteractionGridContainer.js, public/js/p3/widget/PathwaysMemoryGridContainer.js, public/js/p3/widget/Phylogeny.js, public/js/p3/widget/ProteinFamiliesGridContainer.js, public/js/p3/widget/SequenceGridContainer.js, public/js/p3/widget/SpecialtyGeneGridContainer.js, public/js/p3/widget/SubSystemsMemoryGridContainer.js, public/js/p3/widget/TaxonomyTreeGridContainer.js, public/js/p3/widget/TranscriptomicsExperimentGridContainer.js
addressed issue PATRIC3/patric3_webiste#2023
=> Add link to User Guides on all appropriate tabs

public/js/p3/widget/GridContainer.js, public/js/p3/widget/Phylogeny.js, public/js/p3/widget/app/ComprehensiveGenomeAnalysis.js, public/js/p3/widget/app/templates/ComprehensiveGenomeAnalysis.html
=> use info icon in stead of question mask

public/js/p3/resources/WorkspaceManager.css, public/js/p3/widget/viewer/Seq.js
Added a disabled class to the ActionButtonWrapper and then used it to disable the view tracks button until the promise is fulfilled on the call to workspace.
=> Fix for issues #1960 and #1657

public/js/p3/widget/app/templates/GenomeDistance.html, public/js/p3/widget/app/templates/PhylogeneticTree.html, public/js/p3/widget/app/templates/SeqComparison.html
=> changes in Similar Genome Finder Advanced Parameters

public/js/p3/resources/home-new.css, views/home.ejs, views/p3header.ejs
In addition to these commits I'll need to add additional links to the p3_docs index to provide navigation between these pages now being referenced in docs.patricbrc.org instead of patricbrc.org
=> Changes in Header + Homepage

public/js/p3/widget/app/templates/Annotation.html, public/js/p3/widget/app/templates/ComprehensiveGenomeAnalysis.html
=> added viruses option

public/js/p3/widget/app/IDMapper.js, public/js/p3/widget/app/MetagenomeBinning.js, public/js/p3/widget/app/Reconstruct.js, public/js/p3/widget/app/templates/MetagenomeBinning.html
update description for metagenomic binning service and model reconstruction service; used a default URL for ID mapper service's tutorial. PATRIC3/patric3_website#2031
=> updated description for 2 services and minor change

public/js/p3/widget/WorkspaceObjectSelector.js
This is an important one since it's affecting selection of public/workshop data.  Testing appreciated.
=> fix case where public data is not set

public/js/p3/widget/app/templates/Rnaseq.html
simple fix for help information
=> fixing div name of contrasts

public/js/p3/widget/app/ComprehensiveGenomeAnalysis.js, public/js/p3/widget/app/templates/ComprehensiveGenomeAnalysis.html
Before enabling submit button, make sure contigs file is not empty.
=> In CGA, make sure contigs file is not empty

public/js/p3/widget/app/templates/Annotation.html
=> added genetic code 25 in UI

public/js/p3/widget/app/GenomeAlignment.js, public/js/p3/widget/app/templates/GenomeAlignment.html
This is a simple fix that would be safe for prod.
=> fix seed weight option; fixes PATRIC3/patric3_website#2191

public/js/p3/widget/FeatureOverview.js, public/js/p3/widget/TranscriptomicsGeneGrid.js, public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/app/templates/ComprehensiveGenomeAnalysis.html, public/js/p3/widget/viewer/PhylogeneticTree.js
added genetic code 25 in UI (for CAS) PATRIC3/patric3_website#2193
=> a few bug fixes

public/js/p3/widget/app/CodonTree.js, public/js/p3/widget/app/MetagenomicReadMapping.js, public/js/p3/widget/app/templates/CodonTree.html, public/js/p3/widget/app/templates/MetagenomicReadMapping.html
first version, for internal testing only.
=> UIs for codon tree and read mapping

public/js/p3/widget/app/FunctionalClassification.js, public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/templates/FunctionalClassification.html, public/js/p3/widget/app/templates/TaxonomicClassification.html
initial check in, for internal testing only.
=> Taxonomic Classification and Functional Classification UIs.

public/js/p3/widget/app/TaxonomicClassification.js, public/js/p3/widget/app/templates/TaxonomicClassification.html, views/p3header.ejs
added "Metagenomics" section;
moved Metagenome Binning to this section;
added link to Taxonomic Classification.
=> update Services menu

public/js/p3/widget/app/templates/MetagenomicReadMapping.html, public/js/p3/widget/app/templates/PhylogeneticTree.html
for metagenomic read mapping and tree service UIs.
=> minor edits on option/text

public/js/p3/resources/DataItemFormatter.css, public/js/p3/widget/ColumnsGenome.js, public/js/p3/widget/DataItemFormatter.js
This just adds the QC fields to the meta and table.  I'll need @hyoo's help in making them part of the default list returned by Solr.
=> add genome quality fields

public/js/p3/widget/app/FastqUtil.js, public/js/p3/widget/app/templates/FastqUtil.html, views/p3header.ejs
New fastq utils service interface
=> Fastq Utils interface

public/js/p3/widget/app/Assembly2.js, public/js/p3/widget/app/templates/Assembly.html, public/js/p3/widget/app/templates/Assembly2.html
for both paired read input and single read input section.
=> updated options for platform list (for new assembly UI)

public/js/p3/resources/WorkspaceManager.css, public/js/p3/widget/ActionBar.js, public/js/p3/widget/WorkspaceBrowser.js
=> disable rename (temporarily)

public/js/p3/widget/app/Rnaseq.js, public/js/p3/widget/app/templates/Rnaseq.html
=> deprecate Rockhopper option

public/js/p3/widget/app/Assembly2.js, public/js/p3/widget/app/templates/Assembly2.html
(https://github.com/olsonanl/app_service/blob/dev-slurm/app_specs/GenomeAssembly2.json)
=> update UI based on recent changes in JSON specification.

public/js/p3/widget/app/templates/FastqUtil.html
fixes bug in fastq utils interface that allows job submission without specifying a pipeline step.
=> set pipeline counter to zero

public/assets/js/patric_ui.js, views/devp3header.ejs
@ba21, I think this is the request and behavior needed for the feedback form.  See: https://github.com/nconrad/p3_web/blob/f10031967d5e3e3263d7c8b5d1face9f17fff1a1/public/assets/js/patric_ui.js#L9-L68
When you are ready, I'll put it on alpha.
=> wire the new feedback form to reportProblem

public/js/p3/widget/app/Assembly2.js
This is for the new assembly service UI.
=> make sure Boolean type is returned, used to be string.

views/p3header.ejs
Jim asked to move the location of this link.
=> Move Cite PATRIC link to different location in hamburger menu

public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/WorkspaceObjectSelector.js, public/js/p3/widget/app/ComprehensiveGenomeAnalysis.js, public/js/p3/widget/app/templates/ComprehensiveGenomeAnalysis.html, public/js/p3/widget/templates/WorkspaceObjectSelector.html, public/js/p3/widget/viewer/ComprehensiveGenomeAnalysis.js
=> bugs fix and changes on CGA form 

public/js/p3/widget/app/templates/ComprehensiveGenomeAnalysis.html
=> minor fix on resizing/CSS issue.

public/js/p3/widget/TranscriptomicsGeneHeatmapContainerNew.js
- also fixes the icon/toolbar overlapping in subsystem view
=> fix rna seq log-ratio/z-score filter coloring

public/js/p3/widget/JobsGrid.js
https://github.com/PATRIC3/patric3_website/issues/2338
=> Update default display of Jobs List

public/js/p3/widget/FeatureOverview.js, public/js/p3/widget/app/ComprehensiveGenomeAnalysis.js
- Check for unique EC Numbers and display results: [#2318](https://github.com/PATRIC3/patric3_website/issues/2318)
- Check for unique Pathways and display results: [#2318](https://github.com/PATRIC3/patric3_website/issues/2318)
- Check for unique Subsystems and display subsystem_names + role_names: [#2318](https://github.com/PATRIC3/patric3_website/issues/2318)
- Update CGA Tutorial Link to revised edition
=> Cumulative Fixes

public/js/p3/widget/FeatureOverview.js
https://github.com/PATRIC3/patric3_website/issues/2319
=> External Identifiers ID Mapping

public/js/p3/widget/FeatureOverview.js, public/js/p3/widget/formatter.js
https://github.com/PATRIC3/patric3_website/issues/2319
=> External Database Identifiers

public/js/p3/resources/assembly.css, public/js/p3/widget/SelectedTable.js, public/js/p3/widget/app/GenomeAlignment.js, public/js/p3/widget/app/templates/GenomeAlignment.html
Reverts PATRIC3/p3_web#946
This should have went to develop.
=> Revert "genome alignment: add additional notices/validation; fixes PATRIC3/pa…"

public/js/p3/widget/WorkspaceObjectSelector.js
see PATRIC3/patric3_website#2320
=> object selector: show hidden folders automatically when browsing for contigs

public/js/p3/widget/ProteinFamiliesHeatmapContainerNew.js
Per comments with Neal Conrad, I used getState() to get the matrix, rows, and columns for saving the JSON version of the heatmap.
=> #961 Used _self.chart.getState() throughout saving the JSON.

public/js/p3/widget/app/templates/Annotation.html
https://github.com/PATRIC3/patric3_website/issues/2349
and 
https://github.com/PATRIC3/patric3_website/issues/2350
=> Update Annotation template

public/js/p3/widget/app/ComprehensiveSARS2Analysis.js
Had to make two requests instead of one to get additional title of experiment using SRA resources.
https://gist.github.com/tomsing1/074e10905a89072144227f4670377d31
=> update verification against SRA

public/js/p3/widget/app/ComprehensiveSARS2Analysis.js
updating validation to re enable input field on failure of validation
=> Sars cov 2

public/js/p3/widget/GenomeNameSelector.js
=> remove space from query; PATRIC3/patric3_website#2379

public/js/p3/widget/DataItemFormatter.js, public/js/p3/widget/GenomeOverview.js, public/js/p3/widget/TaxonomyOverview.js, public/js/p3/widget/templates/GenomeOverview.html, public/js/p3/widget/templates/TaxonomyOverview.html
https://github.com/PATRIC3/patric3_website/issues/2363
- Feature Overview: Add 'insert date' and 'date modified' data to feature summary
https://github.com/PATRIC3/patric3_website/issues/2375
- Taxon Overview: Add BEI Resource link and search dynamically by 'taxon_name'
- Genome Overview: Add BEI Resource link and search dynamically by 'genome_name'
=> Add dates and BEI links

public/js/p3/widget/app/AppBase.js, public/js/p3/widget/app/Variation.js, public/js/p3/widget/app/templates/Variation.html
The server side processing should all be present.
=> Added SRA to variation service.

public/js/p3/widget/app/Tnseq.js, public/js/p3/widget/app/templates/Tnseq.html
The server side processing should be in place now, so we can add the front end.
=> Upgrade tnseq to transit3 with protocol and primer.

public/js/p3/widget/WorkspaceBrowser.js, public/js/p3/widget/viewer/MSAView.js
Please integrate into BV-BRC as well as PATRIC. This is the viewer for aligned fasta files that the MSA service produces.
=> MSA viewer for aligned fasta files.
